import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], weight:"400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  login,
  signup,
  admin
}) {

  const isRegistered = false

  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
        {isRegistered ? login : signup}

      </body>
    </html>
  );
}
