import { Roboto } from "next/font/google";
import "./globals.css";
import { LoginContextProvider } from "@/context/LoginContext";
import { WishlistContextProvider } from "@/context/WishlistContext";
import InitializeContextData from "@/components/InitializeContextData";
import { ShoppingCartContexttProvider } from "@/context/ShoppingCartContext";

const roboto = Roboto({ subsets: ["latin"], weight:"400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  login,
  signup,
  admin
}) {

  // const isRegistered = false

  return (
    <html lang="en">
      <body className={roboto.className}>
        <LoginContextProvider>
          <WishlistContextProvider>
            <ShoppingCartContexttProvider>
            <InitializeContextData />
            {children}
            {/* {isRegistered ? login : signup} */}
            </ShoppingCartContexttProvider>
          </WishlistContextProvider>
        </LoginContextProvider>
      </body>
    </html>
  );
}
